### ISSUE TITLE
Is it possible to prune convolution layers in TF now?

### ISSUE THREAD

**Issue by jcggg** [garion9013/impl-pruning-TF#12] opened 2017-07-23 13:30 UTC
Hi garion9013, your work is a nice try to implement network pruning in TensorFlow. 
However, I look through the code and find that you only use SparseVariable to prune fully-connected layers.
I wonder that if it is possible to prune convolution layers in TF now? [With or without modify the source code]

**Comment by younghwanoh** [comment] 2017-07-23 16:26
This issue seems to be a duplicate of #4 . But, here are some updated comments.
Unfortunately, it's not easy to do so now. It might be possible only with quite much modification on TF's C++/CUDA computation kernel. Or, you can manually implement kernel with numpy + scikit.sparse libraries. But, with TF's official programming style? (e.g. Python, tf.Session, and TF's ops) you might not. Because, to implement sparse convolution, you should change the internal steps of convolution kernel. (convolutional lowering & sparse matrix ops) I didn't carefully checked the up-to-date version of TF, but they may not.

**Closed as completed** 2017-08-12 05:47 UTC
